name: JBoss Parent CI Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'NOTICE'
      - 'README*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: build

    steps:
      - name: Check out project
        uses: actions/checkout@v4
        with:
          path: jboss-parent-pom

      - name: Set up the JDKs
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          architecture: x64
          java-version: |
            8
            11
            17

      - name: Install the parent POM snapshot
        run: |
          cd jboss-parent-pom
          mvn -B -ntp install

      - name: Check out WildFly Common
        uses: actions/checkout@v4
        with:
          repository: wildfly/wildfly-common
          path: wildfly-common

      - name: Test WildFly Common with updated parent
        run: |
          cd wildfly-common
          mvn -B -ntp versions:update-parent -DallowSnapshots=true -N
          git diff pom.xml
          mvn -B -ntp install -Djava8.home=${{env.JAVA_HOME_8_X64}} -Djava11.home=${{env.JAVA_HOME_11_X64}}

      - name: Check out WildFly Maven Plugin
        uses: actions/checkout@v4
        with:
          repository: wildfly/wildfly-maven-plugin
          path: wildfly-maven-plugin

      - name: Test WildFly Maven Plugin with updated parent
        run: |
          cd wildfly-maven-plugin
          mvn -B -ntp versions:update-parent -DallowSnapshots=true -N
          git diff pom.xml
          mvn -B -ntp install -Djava8.home=${{env.JAVA_HOME_8_X64}} -Djava11.home=${{env.JAVA_HOME_11_X64}}

      - name: Check out JBoss Modules
        uses: actions/checkout@v4
        with:
          repository: jboss-modules/jboss-modules
          path: jboss-modules

      - name: Test JBoss Modules with updated parent
        run: |
          cd jboss-modules
          mvn -B -ntp versions:update-parent -DallowSnapshots=true -N
          git diff pom.xml
          mvn -B -ntp install -Djava8.home=${{env.JAVA_HOME_8_X64}} -Djava11.home=${{env.JAVA_HOME_11_X64}}
